name: WhiteListPerm
main: com.coolv1994.whitelistperm.WhiteListPerm
version: 1.2
description: White-list players with a permission.
website: http://www.coolv1994.com/
author: CoolV1994
loadbefore: [PermissionsEx]
commands:
  wlon:
    description: Enable white-list mode.
    usage: /<command>
    permission: whitelist.admin
    permission-message: You do not have permission to use this command.
  wloff:
    description: Disable white-list mode.
    usage: /<command>
    permission: whitelist.admin
    permission-message: You do not have permission to use this command.
  wlmsg:
    description: Change the white-listed message.
    usage: /<command> <message>
    permission: whitelist.admin
    permission-message: You do not have permission to use this command.
permissions:
  whitelist.join:
    description: Permssion to join the server in white-list mode.
    default: false
  whitelist.admin:
    description: Enable/Disable white-list mode and change message.
    default: op
